import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Stack;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;


public class cardDeckGenerator {
	
	//Draw pile
	public static Stack<Integer> drawPile = new Stack<>();
	
	/**
	 * System will label the following
	 * Jack = 11
	 * Queen == 12
	 * King == 13
	 * 
	 * Constructor that will create a draw pile that is randomized with all cards needed for game
	 */
	public cardDeckGenerator(){

		List<Integer> deck = new ArrayList<>();
		
		for (int i = 1; i <= 13; i++) {
			for(int j = 0; j < 4; j++) {
				deck.add(i);
			}
		}
		
		//Shuffle using Collections
		Collections.shuffle(deck);
		
		//Add shuffled to pile
		drawPile.addAll(deck);
		
		
		//-------------------------------------------------------------------------------------------------------
		//First Method, didnt like how it came out, felt as if it was bias
		//Kept it if wanted to be reused later
		
//		Map<Integer, Integer> countMap = new HashMap<>();
//		Random rand = new Random();
		
//		//Variables
//		int min = 1;
//		int max = 13;
//		int limitPerNumber = 4;
//		int totalCards = 52;
		
//		for (int i = 0; i < max; i++) {
//			countMap.put(i + 1, 0);
//		}
		
//		Stack<Integer> drawPile = new Stack<>();
//		
//		for (int i = 0; i < max; i++) {
//			countMap.put(i + 1, 0);
//		}
//		
//		for (int i = 0; i < totalCards; i++) {
//			int randomNumber = rand.nextInt(max - min + 1) + min;
//	        int currentValue = countMap.get(randomNumber);
//	        if (currentValue < limitPerNumber) {
//	        	drawPile.push(randomNumber);
//	        	countMap.replace(randomNumber, currentValue + 1);
//	        } else {
//	        	//Remove i by 1 to allocate for removal of 
//	        	i-- ; 
//	        }
//		}      
//		System.out.println(countMap);
		
		
	}
	
	/**
	 * Returns a Integer value representing a card.
	 * This value is generated by popping the top element of an already
	 * randomized stack
	 * @return Random Integer value
	 */
	public static int getCard(){
		return drawPile.pop();
	}
	
	/**
	 * Creates a list representing a deck of cards within the given size
	 * Each card added to deck is returned by getCard(), which will pop 
	 * a card from the already randomized stack method
	 * @param deckSize parameter set at beginning of game to determine deck size
	 * @return a randomized deck for player
	 */
	public static List<Integer> createDeck(int deckSize) {
		List<Integer> deck = new ArrayList<>();
		for (int i = 0; i < deckSize; i++) {
			deck.add(getCard());
		}
		
		return deck;
	}
	
	/**
	 * Debug Main Method
	 * @param args
	 */
	public static void main(String[] args) {
		cardDeckGenerator intl = new cardDeckGenerator(); 
		System.out.println(drawPile.toString());
		System.out.println(createDeck(5));
		System.out.println( drawPile.toString());
	}
}
